### ISSUE TITLE
Different order in style tag is seen as a difference

### ISSUE THREAD

**Issue by ortrails** [AngleSharp/AngleSharp.Diffing#17]
Hey guys! I've been doing an html comparision of documents which only differ in the order of items in various style tags. I thought that the default diff options should prevent a difference from being detected in that situation. The difference looks like this in one html doc:
`<td style="width:25%;background-color:#C0C0C0">Location</td>`

...and this in the other
`<td style="background-color:#C0C0C0;width:25%">Location</td>`

Is there an option I can turn on to prevent this from being identified?
I suspect that the problem may be related to dropping the trailing semicolon after the final item in the style. The library I am using to output HTML does this, perhaps to reduce file size a bit.

UPDATE: Actually the behavior I'm seeing is inconsistent results in my test. Sometimes I get 5 diffs, other times 4, other times 0.

Thanks!

**Comment by egil** [comment]
The question is, whether or not it is actually safe to ignore the order of the individual style definitions in a style attribute, if the same style definition is not defined twice (e.g. where the latter overrides the first). 

@FlorianRappl you are much more of an HTML5 spec expert than me, can you perhaps answer this?

**Comment by FlorianRappl** [comment]
Yeah sorting there is stable. The exception is vendor specific prefixes. Also if the same prop is used twice the order matters (usually this is to first have a legacy def and then a modern def, do that the modern one overrides the legacy and is otherwise ignored).

I'll think about some logic here that should reflect that.

**Comment by ortrails** [comment]
Thanks for the help guys. Much appreciated.

**Comment by egil** [comment]
@ortrails, let me keep this open and around. If @FlorianRappl has a good way for us add support for this in a safe way, then its a good addition.

**Comment by egil** [comment]
Since we cannot guarantee that this will always work, my suggestion is instead that we just create a customized [StyleAttributeComparer.cs](https://github.com/AngleSharp/AngleSharp.Diffing/blob/devel/src/AngleSharp.Diffing/Strategies/AttributeStrategies/StyleAttributeComparer.cs) that does what you need. Then, when you want to do a comparison, simply register the custom style attribute comparer and then you have that feature.

@SebastianStehle / @ortrails, if you want to submit a PR with the custom `OrderedStyleAttributeComparer` (just a suggestion for a name) or simply want to build one and share it here that would be great.
