### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by igitur** [AngleSharp/AngleSharp.Diffing#41]
Hi,

Would it be possible to release a version with upgraded dependencies:
- AngleSharp >= v1
- AngleSharp.Css >= v1 (which I realise is still in alpha)

The current AngleSharp.Css dependency has a further dependency on AngleSharp < 0.18, which makes me very hesitant to upgrade AngleSharp to v1+.

thanks

**Comment by egil** [comment]
Hey @igitur,

The problem is that we cannot release a stable version when we have a dependency on an unstable package (anglesharp.css).

I am pretty certain that @FlorianRappl considers AngleSharp.Css stable, but he is keeping the "alpha" label on the library because the implementation is not complete, that is, the full CSS specification is not implemented.
